name: music_streaming_app
description: Stream music on your phone.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayer: ^0.5.2
  google_sign_in: ^4.0.0
  firebase_core: ^0.3.0
  firebase_auth: ^0.8.0+1
  http: ^0.12.0+1
  html: "0.13.3+3"
  flutter_redux: ^0.5.3
  flushbar: ^1.2.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  